### ISSUE TITLE
default content styling

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#1]
- [x] Adjust default content styles (default colors, link behavior, buttons, font size, ...) in `styles.css`
- [x] Add fallback font, see https://github.com/adobe/helix-font-fallback-extension#readme
- [x] Add Favicon
- [x] Adjust media breaks, only if really needed

Attention default style is like this page https://www.eder-gmbh.de/unternehmen/geschaeftsfuehrung/ with main content area and sidebar. Homepage and a few other pages have different overall look & feel, we will use a separate template for this, see #4

**Comment by mtilburgadobe** [comment]
Created https://github.com/hlxsites/eder-group/pull/45 for the 2nd Task

**Comment by mtilburgadobe** [comment]
Favicon: https://github.com/hlxsites/eder-group/pull/46

**Comment by mtilburgadobe** [comment]
default styles and media breaks: https://github.com/hlxsites/eder-group/pull/49
