### ISSUE TITLE
[Lightbox] bug in lightbox placement and scrolling

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#106]
Two UI bugs on the lightbox:

- [ ] big image lightbox should be entere on the screen, currently it is at the top
- [x] closing the lightbox view (via "x") makes the page scrolling to the top

**Comment by alexcarol** [comment]
@mhaack regarding the first point (entire screen), that doesn't seem to be true for all pages (https://www.eder-gmbh.de/newstermine/pressemeldungen/detail/hyster-bringt-einen-neuen-gabelhochhubwagen-auf-den-markt only uses a small part of the screen), have you seen any pages where this behaviour needs to be changed?

**Comment by alexcarol** [comment]
As discussed the first issue will be tackled if deemed necessary by QA.
