### ISSUE TITLE
[Site] Implement Column Block

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#11]
- [ ] adjust boilerplate column block with spaces & margins used on the original site
- [ ] style option to add lines in between (see https://www.eder-gmbh.de/unternehmen/geschaeftsbereiche/)
- [ ] style option for wide CTA buttons (see https://www.eder-gmbh.de/unternehmen/geschaeftsbereiche/)

![Screenshot 2022-12-15 at 11 45 23](https://user-images.githubusercontent.com/2643450/207839881-a6f7d80c-a45e-4c0b-b995-b5325e9b2e89.png)

**Comment by mtilburgadobe** [comment]
As discussed on slack, instead of using the boilerplate Columns Block, we introduced a new Block called org-unternehmen that is specific to this page.
