### ISSUE TITLE
Final Items for Gallery

### ISSUE THREAD

**Issue by mtilburgadobe** [hlxsites/eder-group#113]
Initial development was done in #21 , however there were a few functionalities missing from this initial implementation

- [x] Animation of scrolling arrow (arrow moves on hover)
- [x] automatic scrolling without using the button
- [ ] #154
- [x] Allow for scrolling using arrow keys 

https://www.eder-gmbh.de/newstermine/pressemeldungen/detail/karrieretag-bei-eder

**Comment by alexcarol** [comment]
Also pending:
[ ] scrolling using the arrow keys
