### ISSUE TITLE
[Pages] Missing/wrong margins on pages using sidebar

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#123]
Below 1200px, padding around main content is required - currently padding/margin is missing

**Comment by mtilburgadobe** [comment]
@mhaack -> I see padding around the content, and agree it's off... wanted to clarify this is what you're talking about here:

Original:
![Screenshot 2023-02-08 at 09 05 59](https://user-images.githubusercontent.com/77688257/217470759-e0e8ea5b-9905-428f-bd6d-662f25768dec.png)
![Screenshot 2023-02-08 at 09 05 52](https://user-images.githubusercontent.com/77688257/217470802-a4101292-6a8e-48a0-a0de-c20e349451c1.png)

Main:
![Screenshot 2023-02-08 at 09 06 15](https://user-images.githubusercontent.com/77688257/217470858-fca4aa0a-d68c-4a5d-b9f4-5c1078d124b9.png)
![Screenshot 2023-02-08 at 09 05 40](https://user-images.githubusercontent.com/77688257/217470891-f582699a-cb7f-486e-8dae-a573177ca7d8.png)
