### ISSUE TITLE
[Page] Hero font size is wrong

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#132]
![Screenshot 2023-02-01 at 15 57 04](https://user-images.githubusercontent.com/2643450/216077960-489b01ae-7f52-4cd6-9830-58bf281121bc.png)

**Comment by hannessolo** [comment]
![Screenshot 2023-02-01 at 16 50 11](https://user-images.githubusercontent.com/24207564/216093345-416ab4d6-0fb4-4b93-be58-c8dfca5a1c68.png)

Fixed in content
