### ISSUE TITLE
[Press Releases] implement press release overview page

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#18]
See https://www.eder-gmbh.de/newstermine/pressemeldungen/

- [ ] everything is one block
- [ ] filter press releases by meta data
- [ ] display result list
- [ ] support for pagination

This is blocked by #15 & #16

**Comment by regniets** [comment]
[news.csv](https://github.com/hlxsites/eder-group/files/10454427/news.csv)
Hi @mhaack - pls find attached the news export (utf8). should be comprehensive, if you need any more fields, i can provide you with that on short notice.

**Comment by mhaack** [comment]
Thanks, looking into it
