### ISSUE TITLE
[Press Releases] Implement styles for press release content

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#20]
- [x] styles for link lists (see https://www.eder-gmbh.de/newstermine/pressemeldungen/detail/kundenmagazin-der-eder-weihnachtspost-2022/)
- [x] styles for CTA buttons with different colors  - lets only support primary & secondary button styles (see https://www.eder-gmbh.de/newstermine/pressemeldungen/detail/agratec-news-als-e-paper-zum-durchblaettern/ or https://www.eder-gmbh.de/newstermine/pressemeldungen/detail/baumarkt-prospekt-des-eder-profi-baumarkt-in-tuntenhausen-bad-endorf-und-wasserburg/)
- [x] styles for center headlines (see https://www.eder-gmbh.de/newstermine/pressemeldungen/detail/eder-inspektionswochen-in-der-kleingeraetewerkstatt/)
- [x] bullet lists (see https://www.eder-gmbh.de/newstermine/pressemeldungen/detail/eder-feiert-steyr-busfahrt-mit-tollem-rahmenprogramm-zum-steyr-werk-in-st-valentin/)
- [x] "Weitere News" = more news link
- [x] #50 can be done with this one as well

**Comment by mhaack** [comment]
Please also see https://github.com/hlxsites/eder-group/issues/50

**Comment by mtilburgadobe** [comment]
I will do #50 in a separate PR
