### ISSUE TITLE
[Site] Implement social media page

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#22]
See https://www.eder-gmbh.de/newstermine/social-media/

- [x] Standard layout with content
- [x] Facebook channel widget

**Comment by mtilburgadobe** [comment]
@mhaack - looks like the content for newstermine/social-media is not yet in sharepoint.  What is the process for importing it?

**Comment by mhaack** [comment]
No just create this manually does not make much sense to import this with blocks only used on this page.
