### ISSUE TITLE
[Site] Setup DNS & CDN

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#28]
Option a) AEM CS CDN is used, customer is AEM CS customer > requires SKYOPS JIRA for Adobe
Option b) BYOCDN, follow https://git.corp.adobe.com/experience-platform/franklin-delivery-cdn/blob/main/Runbook.md
- [ ] Test CDN invalidation

**Comment by mtilburgadobe** [comment]
From slack, contact for DNS for Eder:

Karin Zipperling
  [23 minutes ago](https://adobe-dx-support.slack.com/archives/C04E2642TEH/p1674032294664359)
Hi all, Markus asked me for a contact at EDER for the DNS change. The contact is [m.brunner@eder-gmbh.de](mailto:m.brunner@eder-gmbh.de) Should you wish to contact him directly, please write in German and cc in [k.zipperling@techdivision.com](mailto:k.zipperling@techdivision.com) [s.regniet@techdivision.com](mailto:s.regniet@techdivision.com) [B.Schiedermeier@eder-gmbh.de](mailto:B.Schiedermeier@eder-gmbh.de) [C.Dettendorfer@eder-gmbh.de](mailto:C.Dettendorfer@eder-gmbh.de)

**Comment by mtilburgadobe** [comment]
Adobe Internal Documentation for Adobe Managed CDN (if necessary)
https://wiki.corp.adobe.com/display/WEM/Adobe+Managed+CDN+for+Franklin+Delivery

**Comment by mtilburgadobe** [comment]
Internal Jira at Adobe: https://jira.corp.adobe.com/browse/SKYOPS-52837
