### ISSUE TITLE
[Careers] Implement job listing & apprenticeship import

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#34]
This is on https://www.eder-karriere.de/ domain and different Git repo & content folder !

- [x] import job listings + meta data in documents
- [x] import apprenticeship listings + meta data in documents
- [x] setup 2x query index

**Comment by regniets** [comment]
[jobs.csv](https://github.com/hlxsites/eder-group/files/10454404/jobs.csv)
Hi @mhaack 
here is an export of the current jobs, could you pls have a look? What i cannot export is the header image on the job detail page, but at least i have the thumbnail.
