### ISSUE TITLE
[Press Releases] Implement special Eder style headline

### ISSUE THREAD

**Issue by mhaack** [hlxsites/eder-group#50]
Some news docs use a special Eder font styled headline. This headline is imported as `h6` and needs to be styled in read using the eder font.

Sample: https://www.eder-gmbh.de/newstermine/pressemeldungen/detail/kundenmagazin-der-eder-weihnachtspost-2022/

**Comment by mtilburgadobe** [comment]
@mhaack - while looking into this one, I noticed that these 'headlines' are using imported fonts, you can find snippets like this in generalSytles.css

`@font-face {
    font-family: bebas_neue_regular;
    src: url(../../Public/Fonts/bebas_neue/bebasneue_regular.eot);
    src: url(../../Public/Fonts/bebas_neue/bebasneue_regular.eot?#iefix) format("embedded-opentype"), url(../../Public/Fonts/bebas_neue/bebasneue_regular.woff2) format("woff2"),
        url(../../Public/Fonts/bebas_neue/bebasneue_regular.woff) format("woff"), url(../../Public/Fonts/bebas_neue/bebasneue_regular.ttf) format("truetype"),
        url(../../Public/Fonts/bebas_neue/bebasneue_regular.svg#bebas_neue_regularregular) format("svg");
    font-weight: 400;
    font-style: normal;
    font-display: swap;
}`

**Comment by mhaack** [comment]
We should add these fonts to the project, I thought we already did this as part of https://github.com/hlxsites/eder-group/issues/1?
We should add them either here or separate issue.

**Comment by mtilburgadobe** [comment]
The only font I see in the project is 'flaticon.woff', in the fonts folder...

Where would I get the fonts from?

**Comment by mhaack** [comment]
Download from the orginal side and put into `fonts` folder in the project
