### ISSUE TITLE
[Homepage] Fix fonts for blocks as per original site

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/eder-group#62]
Site: https://www.eder-gmbh.de/

Sample:
<img width="1139" alt="Screenshot 2023-01-11 at 2 39 05 PM" src="https://user-images.githubusercontent.com/76686725/211764613-19287487-0bdc-47ba-bece-2dd1590feee5.png">

**Comment by mtilburgadobe** [comment]
Hi @asthabh23 -> I don't see a difference between

https://www.eder-gmbh.de/

and

https://main--eder-group--hlxsites.hlx.page/

Is it possible this was fixed?  If not, could you highlight what is different?
